#!/usr/bin/env bash

cp=.

if [ -a ./pom.xml ]; then
  cp=.:$(mvnsavecp)
fi

export CLASSPATH=$cp:~/java_classes

java_cmd="jjs -classpath \"$CLASSPATH\""

if [ "$(command -v drip)" != "" ]; then
    java_cmd="drip -classpath \"$CLASSPATH\" jdk.nashorn.tools.Shell"
fi

$java_cmd "$@"
